bind = $mainMod, RETURN, exec, uwsm app -- $terminal
bind = $mainMod, SPACE, exec, uwsm app -- $menu
bind = $mainMod ALT, SPACE, exec, uwsm app -- walker -s mainmenu

bind = $mainMod SHIFT, F, exec, uwsm app -- $fileManager
bind = $mainMod SHIFT, B, exec, uwsm app -- google-chrome-stable
bind = $mainMod SHIFT, S, exec, uwsm app -- spotify-launcher
bind = $mainMod SHIFT, D, exec, uwsm app -- ghostty --title='lazydocker' --gtk-single-instance=true -e lazydocker

# claude? twitch? email? calendar?

# Toggle vertical/horizontal split in dwindle layout.
# This requires preserve_split = true in the dwindle section of looknfeel.conf
bindd = SUPER SHIFT, \, Toggle split direction, togglesplit

