# Notifications
bindd = $mainMod, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = $mainMod SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = $mainMod CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"
bindd = $mainMod ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = $mainMod SHIFT ALT, COMMA, Invoke last notification, exec, makoctl restore

# Color picker
bindd = $mainMod, PRINT, Color picker, exec, hyprpicker -a

# Copy / Paste (not working everywhere)
bindd = SUPER, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = SUPER, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
# bindd = SUPER CTRL, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard

