# Fallback config, basically. Ideally this will be managed with waypaper
# or a similar application, but this is for when that breaks.

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/nord-street.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpapers/gruvbox_room.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/catppuccin-rainbow-arch.png
    fit_mode = cover
 }

 splash = false
